import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { CHALLENGES, MATERIALS, SCENES, TOOLS, getMaterial, type Challenge } from './content';
import { ENGINE_VERSION, GRID_HEIGHT, GRID_WIDTH, REACTION_RULES, makeSave, sanitizeRemix, validateSave, type LabCommand, type WorldSummary } from './lab-core';
import { eazoRuntime } from './eazo';
import { audio } from './audio';
import { specimenFor } from './specimens';
import matterSpecimens from './assets/specimens/hero-cluster.webp';
import heroField from './assets/specimens/hero-field.webp';
import { HomeScreen } from './HomeScreen';
import magneticBloom from './assets/reels/magnetic-bloom.mp4';
import inkCollision from './assets/reels/ink-collision.mp4';
import liquidVortex from './assets/reels/liquid-vortex.mp4';

type View = 'lab' | 'challenges' | 'atlas';
type Notice = { kind: 'good' | 'warn'; text: string } | null;
type DiscoveryToast = { rule: (typeof REACTION_RULES)[number]; isNew: boolean };
const EMPTY: WorldSummary = { tick: 0, activeCellCount: 0, worldChecksum: '00000000', renderBufferChecksum: '00000000', counts: {}, reactions: [], pixels: new Uint8Array(GRID_WIDTH * GRID_HEIGHT) };
const SAVE_KEY = 'weird-matter-lab.save.current';
const SAVE_PREVIOUS_KEY = 'weird-matter-lab.save.previous';
const SAVE_TEMP_KEY = 'weird-matter-lab.save.temporary';
const MUTE_KEY = 'weird-matter-lab.muted';
const DISCOVERY_KEY = 'weird-matter-lab.discoveries';
const MATTER_REELS = [
  { id: 'magnetic-bloom', eyebrow: 'MAGNETIC · 06 SEC', title: 'Liquid grows teeth.', note: 'Ferrofluid turns an invisible field into a black, living landscape.', src: magneticBloom, credit: 'Film Composite · Pexels' },
  { id: 'ink-collision', eyebrow: 'COLLISION · 06 SEC', title: 'Yellow meets the void.', note: 'Two clouds become one irreversible shape before the first sentence ends.', src: inkCollision, credit: 'Engin Akyurt · Pexels' },
  { id: 'liquid-vortex', eyebrow: 'DIFFUSION · 06 SEC', title: 'A storm inside one drop.', note: 'Blue and green reveal currents that were present but impossible to see.', src: liquidVortex, credit: 'Engin Akyurt · Pexels' },
] as const;
const hashJson = (value: unknown) => { let hash = 2166136261; for (const byte of new TextEncoder().encode(JSON.stringify(value))) hash = Math.imul(hash ^ byte, 16777619); return (hash >>> 0).toString(16).padStart(8, '0'); };
const download = (name: string, data: string) => { const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([data], { type: 'application/json' })); anchor.download = name; anchor.click(); URL.revokeObjectURL(anchor.href); };

export function App() {
  const workerRef = useRef<Worker | null>(null), canvasRef = useRef<HTMLCanvasElement | null>(null), pausedRef = useRef(false);
  const pendingRef = useRef<LabCommand[]>([]), commandLogRef = useRef<LabCommand[]>([]), redoRef = useRef<LabCommand[][]>([]);
  const undoBatchRef = useRef<number[]>([]), activeStrokeSizeRef = useRef(0);
  const [summary, setSummary] = useState(EMPTY), [materialId, setMaterialId] = useState('sand');
  const [tool, setTool] = useState<(typeof TOOLS)[number]>('brush'), [paused, setPaused] = useState(false);
  const [view, setView] = useState<View>('lab'), [challenge, setChallenge] = useState<Challenge>(CHALLENGES[0]!);
  const [intro, setIntro] = useState(true);
  const [hintLevel, setHintLevel] = useState(0), [search, setSearch] = useState(''), [notice, setNotice] = useState<Notice>(null);
  const [resultOpen, setResultOpen] = useState(false), [materialOpen, setMaterialOpen] = useState(false), [toolsOpen, setToolsOpen] = useState(false), [notebookOpen, setNotebookOpen] = useState(false);
  const [sceneId, setSceneId] = useState(SCENES[11]!.id), [host, setHost] = useState<'web' | 'mobile'>('web');
  const [online, setOnline] = useState(navigator.onLine), [quality, setQuality] = useState<'FULL' | 'REDUCED'>('FULL');
  const [reducedMotion] = useState(() => window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  const [discoveries, setDiscoveries] = useState<string[]>(() => { try { const value = JSON.parse(localStorage.getItem(DISCOVERY_KEY) ?? '[]') as unknown; return Array.isArray(value) ? value.filter((id): id is string => typeof id === 'string' && REACTION_RULES.some((rule) => rule.id === id)) : []; } catch { return []; } });
  const [discoveryToast, setDiscoveryToast] = useState<DiscoveryToast | null>(null), [reactionChain, setReactionChain] = useState(0);
  const [muted, setMuted] = useState(() => {
    const stored = localStorage.getItem(MUTE_KEY);
    if (stored === 'true') return true;
    if (stored === 'false') return false;
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  });
  const [viewMode, setViewMode] = useState<'normal' | 'heat' | 'outline'>('normal');
  const send = useCallback((type: 'reset' | 'step' | 'restore', extra: Record<string, unknown> = {}) => workerRef.current?.postMessage({ type, ...extra }), []);
  const transition = useCallback((update: () => void) => { const start = (document as Document & { startViewTransition?: (callback: () => void) => unknown }).startViewTransition; if (reducedMotion || !start) update(); else start.call(document, update); }, [reducedMotion]);

  useEffect(() => {
    const worker = new Worker(new URL('./simulation.worker.ts', import.meta.url), { type: 'module' });
    worker.onmessage = (event: MessageEvent<WorldSummary>) => setSummary(event.data); workerRef.current = worker; send('reset');
    const timer = window.setInterval(() => { if (!pausedRef.current) send('step', { commands: pendingRef.current.splice(0) }); }, 33);
    return () => { window.clearInterval(timer); worker.terminate(); workerRef.current = null; };
  }, [send]);
  useEffect(() => { pausedRef.current = paused; }, [paused]);
  useEffect(() => { audio.setMuted(muted); localStorage.setItem(MUTE_KEY, String(muted)); }, [muted]);
  useEffect(() => { localStorage.setItem(DISCOVERY_KEY, JSON.stringify(discoveries)); }, [discoveries]);
  useEffect(() => { if (!discoveryToast) return; const timer = window.setTimeout(() => setDiscoveryToast(null), 3200); return () => window.clearTimeout(timer); }, [discoveryToast]);
  useEffect(() => { if (!reactionChain) return; const timer = window.setTimeout(() => setReactionChain(0), 6500); return () => window.clearTimeout(timer); }, [reactionChain]);
  useEffect(() => { if (materialOpen || toolsOpen || notebookOpen || resultOpen) return; const frame = window.requestAnimationFrame(() => window.scrollTo(0, 0)); return () => window.cancelAnimationFrame(frame); }, [materialOpen, notebookOpen, resultOpen, toolsOpen]);
  useEffect(() => {
    void eazoRuntime.platform().then(setHost); const updateOnline = () => setOnline(navigator.onLine);
    window.addEventListener('online', updateOnline); window.addEventListener('offline', updateOnline);
    if ('serviceWorker' in navigator) {
      if (import.meta.env.PROD) navigator.serviceWorker.register('./sw.js').catch(() => setNotice({ kind: 'warn', text: 'Offline cache will finish on the next visit.' }));
      else void navigator.serviceWorker.getRegistrations().then((items) => Promise.all(items.map((item) => item.unregister())));
    }
    const deviceMemory = (navigator as Navigator & { deviceMemory?: number }).deviceMemory ?? 8;
    if (navigator.hardwareConcurrency <= 4 || deviceMemory <= 4) setQuality('REDUCED');
    return () => { window.removeEventListener('online', updateOnline); window.removeEventListener('offline', updateOnline); };
  }, []);
  useEffect(() => {
    const canvas = canvasRef.current, context = canvas?.getContext('2d', { alpha: false }); if (!canvas || !context) return;
    canvas.width = GRID_WIDTH; canvas.height = GRID_HEIGHT; const image = context.createImageData(GRID_WIDTH, GRID_HEIGHT); const palette = ['#F4F0E6', ...MATERIALS.map((item) => item.color)];
    for (let index = 0; index < summary.pixels.length; index += 1) { const color = palette[summary.pixels[index] ?? 0] ?? '#ff00ff'; const rgb = color.match(/[a-f\d]{2}/gi)?.map((part) => Number.parseInt(part, 16)) ?? [255, 0, 255]; const offset = index * 4, heat = viewMode === 'heat' && (summary.pixels[index] ?? 0) > 0; image.data[offset] = heat ? 255 : rgb[0]!; image.data[offset + 1] = heat ? Math.min(190, rgb[1]!) : rgb[1]!; image.data[offset + 2] = heat ? 70 : rgb[2]!; image.data[offset + 3] = 255; }
    context.putImageData(image, 0, 0);
  }, [summary, viewMode]);
  const lastReactionTickRef = useRef(0), lastReactionAtRef = useRef(0), completedChallengeRef = useRef<string | null>(null), discoveredRef = useRef(new Set(discoveries));
  useEffect(() => {
    if (summary.reactions.length === 0 || summary.tick === lastReactionTickRef.current) return;
    lastReactionTickRef.current = summary.tick;
    const newRules = [...new Set(summary.reactions.map((event) => event.reactionId))]
      .map((reactionId) => REACTION_RULES.find((item) => item.id === reactionId))
      .filter((rule): rule is (typeof REACTION_RULES)[number] => rule !== undefined && !discoveredRef.current.has(rule.id));
    if (newRules.length === 0) return;
    for (const rule of newRules) discoveredRef.current.add(rule.id);
    setDiscoveries([...discoveredRef.current]);
    setDiscoveryToast({ rule: newRules.at(-1)!, isNew: true });
    audio.reaction();
    const currentTime = performance.now();
    setReactionChain((value) => currentTime - lastReactionAtRef.current < 6500 ? Math.min(9, value + newRules.length) : newRules.length);
    lastReactionAtRef.current = currentTime;
  }, [summary]);
  useEffect(() => { if ((summary.counts[challenge.goal.materialId] ?? 0) >= challenge.goal.count && summary.tick > 1 && completedChallengeRef.current !== challenge.id) { completedChallengeRef.current = challenge.id; setPaused(true); setResultOpen(true); audio.success(); } }, [challenge, summary]);

  const filteredMaterials = useMemo(() => MATERIALS.filter((item) => !search || `${item.name} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const currentMaterial = getMaterial(materialId), goalCount = summary.counts[challenge.goal.materialId] ?? 0;
  const nextDiscovery = REACTION_RULES.find((rule) => !discoveries.includes(rule.id)) ?? REACTION_RULES[summary.tick % REACTION_RULES.length]!;
  const finishStroke = () => { if (activeStrokeSizeRef.current > 0) undoBatchRef.current.push(activeStrokeSizeRef.current); activeStrokeSizeRef.current = 0; };
  const dropMysteryPair = () => { finishStroke(); const y = 28 + summary.tick % 46, commands: LabCommand[] = [{ type: 'paint', materialId: nextDiscovery.a, x: Math.floor(GRID_WIDTH / 2) - 4, y, radius: 6 }, { type: 'paint', materialId: nextDiscovery.b, x: Math.floor(GRID_WIDTH / 2) + 4, y, radius: 6 }]; pendingRef.current.push(...commands); commandLogRef.current.push(...commands); undoBatchRef.current.push(commands.length); redoRef.current = []; setMaterialId(nextDiscovery.b); setTool('brush'); setPaused(false); setNotebookOpen(false); setNotice({ kind: 'good', text: `Mystery pair dropped: ${getMaterial(nextDiscovery.a).name} + ${getMaterial(nextDiscovery.b).name}. Watch their boundary.` }); };
  const onPointer = (event: React.PointerEvent<HTMLCanvasElement>) => {
    if (event.buttons === 0 && event.type !== 'pointerdown') return;
    if (event.type === 'pointerdown') { finishStroke(); event.currentTarget.setPointerCapture(event.pointerId); }
    const bounds = event.currentTarget.getBoundingClientRect(), x = Math.floor((event.clientX - bounds.left) / bounds.width * GRID_WIDTH), y = Math.floor((event.clientY - bounds.top) / bounds.height * GRID_HEIGHT);
    const sampledValue = summary.pixels[y * GRID_WIDTH + x] ?? 0, sampledMaterial = sampledValue > 0 ? MATERIALS[sampledValue - 1] : undefined;
    if (tool === 'pick' || tool === 'copy' || tool === 'measure') {
      if (event.type !== 'pointerdown') return;
      audio.unlock(); audio.select();
      if (tool === 'measure') { setNotice({ kind: sampledMaterial ? 'good' : 'warn', text: sampledMaterial ? `${sampledMaterial.name} at ${x},${y} · ${summary.counts[sampledMaterial.id] ?? 0} cells in this world.` : `Empty space at ${x},${y}.` }); return; }
      if (!sampledMaterial) { setNotice({ kind: 'warn', text: `${tool === 'copy' ? 'Copy' : 'Pick'} needs a visible material. Try a filled part of the frame.` }); return; }
      setMaterialId(sampledMaterial.id); setTool('brush'); setNotice({ kind: 'good', text: `${tool === 'copy' ? 'Copied' : 'Picked'} ${sampledMaterial.name}. Brush is ready.` }); return;
    }
    const erase = tool === 'erase' || tool === 'vacuum' || tool === 'impact';
    const command: LabCommand = {
      type: tool === 'mix' ? 'stir' : erase ? 'erase' : 'paint',
      materialId: tool === 'heat' ? 'heat' : tool === 'cool' ? 'cold' : tool === 'charge' ? 'electricity' : tool === 'portal' ? 'portal-dust' : materialId,
      x, y,
      radius: tool === 'vacuum' ? 8 : tool === 'impact' ? 6 : tool === 'mix' ? 5 : tool === 'portal' ? 4 : tool === 'erase' ? 3 : 2,
    };
    pendingRef.current.push(command); commandLogRef.current.push(command); activeStrokeSizeRef.current += 1; redoRef.current = []; audio.unlock(); audio.paint();
  };
  const reset = () => { pendingRef.current = []; commandLogRef.current = []; undoBatchRef.current = []; activeStrokeSizeRef.current = 0; redoRef.current = []; completedChallengeRef.current = null; setPaused(false); setResultOpen(false); setHintLevel(0); send('reset'); };
  const selectChallenge = (item: Challenge) => { transition(() => { setChallenge(item); setMaterialId(item.allowed[0] ?? 'sand'); setView('lab'); reset(); }); };
  const undo = () => { finishStroke(); const batchSize = undoBatchRef.current.pop() ?? (commandLogRef.current.length ? 1 : 0); if (!batchSize) return; const commands = commandLogRef.current.splice(-batchSize, batchSize); redoRef.current.push(commands); send('reset'); send('step', { commands: commandLogRef.current }); };
  const redo = () => { const commands = redoRef.current.pop(); if (!commands?.length) return; commandLogRef.current.push(...commands); undoBatchRef.current.push(commands.length); send('step', { commands }); };
  const save = () => { const envelope = makeSave({ tick: summary.tick, cells: summary.pixels } as Parameters<typeof makeSave>[0], challenge.id, commandLogRef.current), previous = localStorage.getItem(SAVE_KEY); localStorage.setItem(SAVE_TEMP_KEY, JSON.stringify(envelope)); if (previous) localStorage.setItem(SAVE_PREVIOUS_KEY, previous); localStorage.setItem(SAVE_KEY, JSON.stringify(envelope)); localStorage.removeItem(SAVE_TEMP_KEY); setNotice({ kind: 'good', text: 'Experiment saved on this device.' }); };
  const restore = () => { for (const key of [SAVE_KEY, SAVE_PREVIOUS_KEY]) try { const raw = localStorage.getItem(key); if (!raw) continue; const value: unknown = JSON.parse(raw); if (validateSave(value)) { const restored = value, savedChallenge = CHALLENGES.find((item) => item.id === restored.challengeId); if (savedChallenge) setChallenge(savedChallenge); commandLogRef.current = restored.commandLog; undoBatchRef.current = restored.commandLog.map(() => 1); activeStrokeSizeRef.current = 0; redoRef.current = []; send('restore', { grid: restored.grid, tick: restored.tick }); setNotice({ kind: 'good', text: 'Last valid experiment restored.' }); return; } } catch { /* try previous */ } setNotice({ kind: 'warn', text: 'No valid save was found. A clean lab is ready.' }); reset(); };
  const exportRemix = () => { const body = { schemaVersion: 1 as const, appId: 'weird-matter-lab' as const, challengeId: challenge.id, seed: 7062026, grid: Array.from(summary.pixels) }; download(`weird-matter-${summary.worldChecksum}.remix.json`, JSON.stringify({ ...body, checksum: hashJson(body) })); setNotice({ kind: 'good', text: 'Safe Remix package exported.' }); };
  const importRemix = async (file: File) => { if (file.size > 2_000_000) { setNotice({ kind: 'warn', text: 'Remix rejected: file is over 2 MB.' }); return; } try { const remix = sanitizeRemix(JSON.parse(await file.text()) as unknown); if (!remix) throw new Error(); transition(() => { setChallenge(CHALLENGES.find((entry) => entry.id === remix.challengeId)!); commandLogRef.current = []; undoBatchRef.current = []; activeStrokeSizeRef.current = 0; redoRef.current = []; send('restore', { grid: remix.grid, tick: 0 }); setView('lab'); setNotice({ kind: 'good', text: 'Remix checked and opened.' }); }); } catch { setNotice({ kind: 'warn', text: 'Remix rejected: invalid fields, material IDs, or checksum.' }); } };
  const shareResult = async () => { try { const result = await eazoRuntime.shareResult(canvasRef.current?.toDataURL('image/png') ?? '', `I completed “${challenge.title}” in Weird Matter Lab · ${summary.worldChecksum}. What will your version become?`); if (result.accepted) setNotice({ kind: 'good', text: 'Sent to Eazo compose.' }); else { exportRemix(); setNotice({ kind: 'warn', text: 'Eazo Mobile is not active, so a local Remix was downloaded.' }); } } catch { exportRemix(); setNotice({ kind: 'warn', text: 'Share was unavailable. Your local Remix is safe.' }); } };
  const navigateTo = (next: View) => { audio.unlock(); audio.ui(); transition(() => setView(next)); };

  if (intro) return <HomeScreen onEnter={() => { audio.unlock(); transition(() => setIntro(false)); }} />;

  return <div className={`lab-app view-${view}`}><a className="skip-link" href="#workspace">Skip to experiment</a>
    <header className="topbar"><button className="brand" onClick={() => navigateTo('lab')} aria-label="Open laboratory"><span className="brand-dot"/>WEIRD MATTER <b>LAB</b></button><div className="runtime"><button className="mute-toggle" onClick={() => { audio.unlock(); setMuted((value) => !value); }} aria-pressed={muted} aria-label={muted ? 'Unmute sound effects' : 'Mute sound effects'} title={muted ? 'Sound off' : 'Sound on'}>{muted ? '🔇' : '🔊'}</button><span className={online ? 'live-dot' : 'offline-dot'}/>{online ? (host === 'mobile' ? 'EAZO LIVE' : 'WEB READY') : 'OFFLINE'} <small>· {quality}</small></div></header>
    <nav className="mode-tabs" aria-label="Main views"><button className={view === 'lab' ? 'active' : ''} onClick={() => navigateTo('lab')}>Experiment</button><button className={view === 'challenges' ? 'active' : ''} onClick={() => navigateTo('challenges')}>Challenges <span>30</span></button><button className={view === 'atlas' ? 'active' : ''} onClick={() => navigateTo('atlas')}>Matter atlas <span>72</span></button></nav>
    {notice && <div className={`notice ${notice.kind}`} role="status"><span>{notice.text}</span><button onClick={() => setNotice(null)} aria-label="Dismiss message">×</button></div>}
    {view === 'lab' && <main id="workspace" className="workspace" tabIndex={-1}>
      <section className="mission" aria-labelledby="mission-title"><div className="mission-field" style={{ backgroundImage: `url(${heroField})` }} aria-hidden="true"/><div><p>CHALLENGE {String(challenge.number).padStart(2, '0')} · {challenge.category.toUpperCase()}</p><h1 id="mission-title">{challenge.title}</h1><span>{challenge.prompt}</span></div><button className="hint-button" onClick={() => setHintLevel((level) => Math.min(3, level + 1))}>{hintLevel ? `Hint ${hintLevel}/3` : 'Need a hint?'}</button>{hintLevel > 0 && <aside className="hint" role="status">{challenge.hints[hintLevel - 1]}</aside>}</section>
      <section className="lab-frame" aria-label="Interactive material simulation"><div className="canvas-toolbar"><div className="view-switch" aria-label="View mode">{(['normal','heat','outline'] as const).map((mode) => <button key={mode} className={viewMode === mode ? 'active' : ''} onClick={() => setViewMode(mode)}>{mode}</button>)}</div><div className="tick-readout">TICK {summary.tick.toLocaleString()} · {summary.activeCellCount.toLocaleString()} CELLS</div></div><div className={`canvas-wrap ${viewMode === 'outline' ? 'outline-view' : ''}`}><canvas ref={canvasRef} onPointerDown={onPointer} onPointerMove={onPointer} onPointerUp={finishStroke} onPointerCancel={finishStroke} aria-label="Matter canvas. Draw with pointer, or use command controls below."/><span className="viewfinder-label" aria-hidden="true">LIVE FRAME · 256×144</span><div className="discovery-hud" aria-label={`${discoveries.length} of ${REACTION_RULES.length} reactions discovered`}><b>{reactionChain > 1 ? `×${reactionChain}` : `${discoveries.length}/${REACTION_RULES.length}`}</b><span>{reactionChain > 1 ? 'CHAIN' : 'REACTIONS'}</span></div>{discoveryToast && <aside className="reaction-toast" role="status"><small>{discoveryToast.isNew ? `NEW REACTION · ${String(discoveries.length).padStart(2, '0')}` : 'CHAIN REACTION'}</small><b>{discoveryToast.rule.title}</b><span>{discoveryToast.rule.prompt}</span></aside>}<div className="goal-meter"><span>{challenge.goal.materialId.replaceAll('-', ' ')}</span><div><i style={{ width: `${Math.min(100, goalCount / challenge.goal.count * 100)}%` }}/></div><b>{Math.min(goalCount, challenge.goal.count)}/{challenge.goal.count}</b></div></div><div className="transport" aria-label="Simulation controls"><button onClick={() => { audio.unlock(); audio.toggle(); setPaused((value) => !value); }} className="transport-primary">{paused ? '▶ Run' : 'Ⅱ Pause'}</button><button onClick={() => { finishStroke(); setPaused(true); send('step', { commands: pendingRef.current.splice(0) }); }}>Step +1</button><button onClick={undo} disabled={!commandLogRef.current.length}>Undo</button><button onClick={redo} disabled={!redoRef.current.length}>Redo</button><button onClick={reset}>Clear</button><button onClick={save}>Save</button><button onClick={restore}>Restore</button></div></section>
      <aside className="control-deck"><section className="tool-rack"><div className="section-heading"><span>TOOLS</span><small>12 instruments</small></div><div>{TOOLS.map((item) => <button key={item} title={item} className={tool === item ? 'active' : ''} onClick={() => { audio.unlock(); audio.select(); setTool(item); }}><span>{({brush:'●',erase:'◇',pick:'⌖',heat:'↑',cool:'↓',mix:'↻',impact:'✦',charge:'ϟ',vacuum:'○',copy:'⊕',measure:'⌁',portal:'↔'} as Record<string,string>)[item]}</span>{item}</button>)}</div></section><section className="material-rack"><div className="section-heading"><span>MATERIAL</span><button onClick={() => setMaterialOpen(true)}>View all 72</button></div><button className="selected-material" onClick={() => setMaterialOpen(true)}><i style={{ backgroundImage: `url(${specimenFor(currentMaterial)})` }}/><span><b>{currentMaterial.name}</b><small>{currentMaterial.state} · {currentMaterial.label}</small></span><em>⌄</em></button><div className="quick-materials">{challenge.allowed.slice(0, 6).map((id) => { const item = getMaterial(id); return <button key={id} className={materialId === id ? 'active' : ''} onClick={() => { audio.unlock(); audio.select(); setMaterialId(id); setTool('brush'); }}><i style={{ backgroundImage: `url(${specimenFor(item)})` }}/><span>{item.name}</span></button>; })}</div></section><section className="save-card"><div><span>LAB NOTEBOOK</span><b>{summary.worldChecksum}</b><small>Engine {ENGINE_VERSION} · {discoveries.length}/{REACTION_RULES.length} reactions</small></div><button className="mystery-button" onClick={dropMysteryPair}>Drop a mystery pair</button><button onClick={exportRemix}>Export Remix</button><label className="import-button">Import<input type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importRemix(file); }}/></label></section></aside>
      <div className="mobile-lab-dock" aria-label="Mobile laboratory controls"><button className="dock-material" onClick={() => setMaterialOpen(true)} aria-label={`Choose material. Current: ${currentMaterial.name}`}><i style={{ backgroundImage: `url(${specimenFor(currentMaterial)})` }}/><span>{currentMaterial.name}</span></button><button className="dock-tool" onClick={() => setToolsOpen(true)} aria-label={`Choose tool. Current: ${tool}`}><b>{({brush:'●',erase:'◇',pick:'⌖',heat:'↑',cool:'↓',mix:'↻',impact:'✦',charge:'ϟ',vacuum:'○',copy:'⊕',measure:'⌁',portal:'↔'} as Record<string,string>)[tool]}</b><span>{tool}</span></button><button className="dock-run" onClick={() => { audio.unlock(); audio.toggle(); setPaused((value) => !value); }} aria-label={paused ? 'Run simulation' : 'Pause simulation'}><b>{paused ? '▶' : 'Ⅱ'}</b><span>{paused ? 'Run' : 'Pause'}</span></button><button onClick={undo} disabled={!commandLogRef.current.length}><b>↶</b><span>Undo</span></button><button onClick={() => setNotebookOpen(true)} aria-label="Open lab notebook"><b>•••</b><span>More</span></button></div>
    </main>}
    {view === 'challenges' && <main className="catalog-page"><div className="catalog-hero"><div><p>30 SMALL QUESTIONS</p><h1>Ridiculous goals.<br/>Real ideas.</h1><span>Every experiment reveals what is fact, what is simplified, and what we invented for play.</span></div><img className="hero-specimens" src={matterSpecimens} alt="A floating cluster of seven imaginary matter specimens"/></div><section className="matter-reels" aria-labelledby="matter-reels-title"><header><div><p>3 VISUAL HOOKS · LICENSED &amp; REMIXED</p><h2 id="matter-reels-title">Watch matter misbehave.</h2></div><span>Six-second loops chosen for an immediate transformation, a readable silhouette, and a finish worth replaying.</span></header><div className="reel-track">{MATTER_REELS.map((reel, index) => <article className="reel-card" key={reel.id}><video autoPlay={!reducedMotion} muted loop playsInline preload={index === 0 ? 'auto' : 'metadata'} aria-label={`${reel.title} visual reference`}><source src={reel.src} type="video/mp4"/></video><div className="reel-shade"/><div className="reel-copy"><small>{reel.eyebrow}</small><h3>{reel.title}</h3><p>{reel.note}</p><span>{reel.credit} · Visual reference, not a recipe</span></div><b aria-hidden="true">0{index + 1}</b></article>)}</div></section><div className="challenge-grid">{CHALLENGES.map((item) => <button key={item.id} onClick={() => selectChallenge(item)}><span>{String(item.number).padStart(2, '0')}</span><div><small>{item.category}</small><h2>{item.title}</h2><p>{item.prompt}</p></div><b>→</b></button>)}</div></main>}
    {view === 'atlas' && <main className="catalog-page"><div className="catalog-hero"><div><p>MATTER ATLAS · CONTENT 1.0</p><h1>72 ways to<br/>change the world.</h1><span>Search behavior, state, and the boundary between science and game logic.</span><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search materials" aria-label="Search materials"/></label></div><img className="hero-specimens" src={matterSpecimens} alt="A floating cluster of seven imaginary matter specimens"/></div><div className="atlas-grid">{filteredMaterials.map((item, index) => <article key={item.id}><div className="matter-swatch" style={{ backgroundImage: `url(${specimenFor(item)})` }}><span>{String(index + 1).padStart(2, '0')}</span><em style={{ background: item.color }}/></div><small>{item.category} · {item.state}</small><h2>{item.name}</h2><p>{item.note}</p><strong className={item.label.toLowerCase()}>{item.label}</strong><button onClick={() => { setMaterialId(item.id); setTool('brush'); transition(() => setView('lab')); }}>Use material</button></article>)}</div></main>}
    <footer><div><b>WEIRD MATTER LAB</b><span>Original educational sandbox · No real-world dangerous recipes</span></div><div><button onClick={() => setSceneId(SCENES[(SCENES.findIndex((item) => item.id === sceneId) + 1) % SCENES.length]!.id)}>{SCENES.find((item) => item.id === sceneId)?.name}</button><span>{online ? 'Offline pack ready' : 'Running offline'}</span></div></footer>
    {materialOpen && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setMaterialOpen(false); }}><section className="material-dialog" role="dialog" aria-modal="true" aria-labelledby="materials-title"><header><div><p>MATTER DRAWER</p><h2 id="materials-title">Choose a material</h2></div><button onClick={() => setMaterialOpen(false)} aria-label="Close material drawer">×</button></header><label className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search all 72 materials"/></label><div>{filteredMaterials.map((item) => <button key={item.id} onClick={() => { setMaterialId(item.id); setTool('brush'); setMaterialOpen(false); }}><i style={{ backgroundImage: `url(${specimenFor(item)})` }}/><span><b>{item.name}</b><small>{item.category} · {item.state}</small></span><em className={item.label.toLowerCase()}>{item.label}</em></button>)}</div></section></div>}
    {toolsOpen && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setToolsOpen(false); }}><section className="tool-dialog" role="dialog" aria-modal="true" aria-labelledby="tools-title"><header><div><p>INSTRUMENT TRAY</p><h2 id="tools-title">Choose a tool</h2></div><button onClick={() => setToolsOpen(false)} aria-label="Close tool tray">×</button></header><div>{TOOLS.map((item) => <button key={item} className={tool === item ? 'active' : ''} onClick={() => { setTool(item); setToolsOpen(false); }}><b>{({brush:'●',erase:'◇',pick:'⌖',heat:'↑',cool:'↓',mix:'↻',impact:'✦',charge:'ϟ',vacuum:'○',copy:'⊕',measure:'⌁',portal:'↔'} as Record<string,string>)[item]}</b><span>{item}</span></button>)}</div></section></div>}
    {notebookOpen && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setNotebookOpen(false); }}><section className="notebook-dialog" role="dialog" aria-modal="true" aria-labelledby="notebook-title"><header><div><p>LAB NOTEBOOK · {summary.worldChecksum}</p><h2 id="notebook-title">Experiment controls</h2></div><button onClick={() => setNotebookOpen(false)} aria-label="Close lab notebook">×</button></header><section className="discovery-deck" aria-labelledby="discovery-title"><div><small>REACTION COLLECTION · {discoveries.length}/{REACTION_RULES.length}</small><h3 id="discovery-title">Next mystery: {nextDiscovery.title}</h3><p>Drop two game materials and watch their boundary. No real-world recipe is shown.</p></div><button onClick={dropMysteryPair}>Drop a mystery pair <span>→</span></button></section><div><button onClick={() => { setPaused(true); send('step', { commands: pendingRef.current.splice(0) }); }}>Step +1</button><button onClick={redo} disabled={!redoRef.current.length}>Redo</button><button onClick={() => { reset(); setNotebookOpen(false); }}>Clear experiment</button><button onClick={save}>Save experiment</button><button onClick={restore}>Restore experiment</button><button onClick={exportRemix}>Export Remix</button><label className="import-button">Import Remix<input type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importRemix(file); }}/></label></div></section></div>}
    {resultOpen && <div className="modal-backdrop result-backdrop"><section className="result-dialog" role="dialog" aria-modal="true" aria-labelledby="result-title"><button className="close-result" onClick={() => setResultOpen(false)} aria-label="Close result">×</button><div className="result-orbit"><span>✦</span><i/><b>{String(challenge.number).padStart(2, '0')}</b></div><p>REACTION COMPLETE</p><h2 id="result-title">{challenge.title}</h2><div className="result-hash">WORLD CHECKSUM · {summary.worldChecksum}</div><div className="knowledge-grid"><article><strong className="fact">FACT</strong><h3>What you saw</h3><p>{challenge.learningPoint}</p></article><article><strong className="simplified">SIMPLIFIED</strong><h3>What we compressed</h3><p>{challenge.modelLimitations}</p></article><article><strong className="fictional">FICTIONAL</strong><h3>Where play begins</h3><p>{challenge.fictionBoundary}</p></article></div><a className="source-link" href={`https://en.wikipedia.org/wiki/Special:Search?search=${encodeURIComponent(challenge.learningPoint)}`} target="_blank" rel="noreferrer">Open source note · {challenge.sourceId}</a><div className="result-actions"><button onClick={shareResult} className="primary-action">Share to Eazo</button><button onClick={exportRemix}>Export Remix</button><button onClick={reset}>Try again</button></div></section></div>}
  </div>;
}
